from bitstring import Bits

PREAMBLE_BYTES = b"\xAA"
PREAMBLE_LENGTH_TX = 33
PREAMBLE_LENGTH_RX = 16
DATA_READY_BYTES = b"\xAC"

SIGNATURE_TX = PREAMBLE_BYTES * PREAMBLE_LENGTH_TX + DATA_READY_BYTES
SIGNATURE_RX = PREAMBLE_BYTES * PREAMBLE_LENGTH_RX + DATA_READY_BYTES
SIGNATURE_TX_BITSTRING = ""
for bit in Bits(SIGNATURE_TX):
    if bit:
        SIGNATURE_TX_BITSTRING += "1"
    else:
        SIGNATURE_TX_BITSTRING += "0"

SIGNATURE_RX_BITSTRING = ""
for bit in Bits(SIGNATURE_RX):
    if bit:
        SIGNATURE_RX_BITSTRING += "1"
    else:
        SIGNATURE_RX_BITSTRING += "0"
